# stack.yml
version: '2'

services:

ghost: build: context: ../.. dockerfile: app/Docker/Dockerfile.release image: arm64v8/ghost:latest restart: always ports: - 3001:2368

volumes:
  - ./content:/var/lib/ghost/content

environment:
  # see https://ghost.org/docs/config/#configuration-options
  database__client: mysql 
  database__connection__host: ghost_db
  database__connection__user: root_name_change_me
  database__connection__password: secure_pasword_change_me
  database__connection__database: ghost
  
# this url value is just an example, and is likely wrong for your environment!
  url: https://yourdomain.com
  # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
  #NODE_ENV: development

labels:
  - traefik.http.routers.blog.rule=Host(`blog.your_domain`)
  - traefik.http.routers.blog.tls=true
  - traefik.http.routers.blog.tls.certresolver=lets-encrypt
  - traefik.port=80

networks:
  - internal
  - web

ghost_db: build: context: ../.. dockerfile: app/Docker/Dockerfile.release image: arm64v8/mariadb:latest restart: always environment: 

# always have a strong passwords
MYSQL_ROOT_USER: root_name_change_me
MYSQL_ROOT_PASSWORD: secure_password_change_me

volumes: - mysql-data:/var/lib/mysql
volumes: mysql-data:
